from typing import Any, Dict, List

TOOL_CATALOG: List[Dict[str, Any]] = [
    {
        "name": "dcf_valuation_tool",
        "category": "valuation",
        "description": "Discounted Cash Flow valuation (two-stage model)",
        "input_schema": "DCFToolInput",
        "output_schema": "DCFValuationOutput",
        "requires_market_data": True,
        "complexity": "medium",
        "tags": ["equity", "intrinsic value", "fundamental", "dcf"],
        "version": "1.0.0",
        "authoritative_source": "Damodaran, CFA Institute",
        "validation_rules": ["terminal_growth < wacc", "positive_free_cash_flows"],
    },
    {
        "name": "black_scholes",
        "category": "derivatives",
        "description": "Black-Scholes-Merton option pricing and Greeks",
        "input_schema": "BlackScholesInput",
        "output_schema": "BlackScholesOutput",
        "requires_market_data": False,
        "complexity": "low",
        "tags": ["options", "greeks", "derivatives"],
        "version": "1.0.0",
        "authoritative_source": "Black & Scholes (1973), Merton",
        "validation_rules": ["positive_volatility", "positive_time_to_expiry"],
    },
    {
        "name": "taylor_rule",
        "category": "macro",
        "description": "Taylor-rule implied policy rate from inflation and output gap",
        "input_schema": "TaylorRuleToolInput",
        "output_schema": "TaylorRuleOutput",
        "requires_market_data": False,
        "complexity": "low",
        "tags": ["macro", "rates", "fed", "monetary policy"],
        "version": "1.0.0",
        "authoritative_source": "Taylor (1993)",
        "validation_rules": ["realistic_inflation_range"],
    },
    {
        "name": "yield_curve_signal",
        "category": "macro",
        "description": "10Y–2Y yield spread and curve recession signal",
        "input_schema": "YieldSpreadToolInput",
        "output_schema": "YieldSpreadOutput",
        "requires_market_data": True,
        "complexity": "low",
        "tags": ["macro", "yield curve", "recession", "rates"],
        "version": "1.0.0",
        "authoritative_source": "Fed / NBER literature",
        "validation_rules": ["positive_yields"],
    },
    {
        "name": "inflation_momentum_tool",
        "category": "macro",
        "description": "CPI-based YoY and momentum inflation signals",
        "input_schema": "InflationMomentumToolInput",
        "output_schema": "InflationMomentumOutput",
        "requires_market_data": True,
        "complexity": "medium",
        "tags": ["macro", "inflation", "cpi"],
        "version": "1.0.0",
        "authoritative_source": "BLS CPI methodology",
        "validation_rules": ["positive_cpi_levels", "sufficient_history"],
    },
    {
        "name": "merton_default_prob",
        "category": "credit",
        "description": "Merton structural default probability and distance to default",
        "input_schema": "MertonDefaultToolInput",
        "output_schema": "MertonDefaultOutput",
        "requires_market_data": False,
        "complexity": "medium",
        "tags": ["credit", "default", "structural", "risk"],
        "version": "1.0.0",
        "authoritative_source": "Merton (1974)",
        "validation_rules": ["positive_equity_debt", "positive_volatility"],
    },
    {
        "name": "credit_spread_analysis_tool",
        "category": "credit",
        "description": "Credit spread, hazard approximation, and rating bucket",
        "input_schema": "CreditSpreadToolInput",
        "output_schema": "CreditSpreadOutput",
        "requires_market_data": False,
        "complexity": "low",
        "tags": ["credit", "spread", "cds", "fixed income"],
        "version": "1.0.0",
        "authoritative_source": "CDS / hazard-rate literature",
        "validation_rules": ["bond_yield_ge_risk_free"],
    },
    {
        "name": "rsi_indicator",
        "category": "technicals",
        "description": "Relative Strength Index with signal bands",
        "input_schema": "RSIToolInput",
        "output_schema": "RSIOutput",
        "requires_market_data": True,
        "complexity": "low",
        "tags": ["technicals", "momentum", "rsi", "equity"],
        "version": "1.0.0",
        "authoritative_source": "Wilder (1978)",
        "validation_rules": ["positive_prices", "min_history"],
    },
    {
        "name": "macd_indicator",
        "category": "technicals",
        "description": "MACD crossover and histogram",
        "input_schema": "MACDToolInput",
        "output_schema": "MACDOutput",
        "requires_market_data": True,
        "complexity": "low",
        "tags": ["technicals", "trend", "macd", "equity"],
        "version": "1.0.0",
        "authoritative_source": "Appel (1979)",
        "validation_rules": ["positive_prices", "min_history"],
    },
    {
        "name": "bollinger_bands",
        "category": "technicals",
        "description": "Bollinger bands and %B",
        "input_schema": "BollingerToolInput",
        "output_schema": "BollingerOutput",
        "requires_market_data": True,
        "complexity": "low",
        "tags": ["technicals", "volatility", "bollinger", "equity"],
        "version": "1.0.0",
        "authoritative_source": "Bollinger (1980s)",
        "validation_rules": ["positive_prices", "min_history"],
    },
]


def get_tool_by_name(name: str) -> Dict[str, Any] | None:
    for entry in TOOL_CATALOG:
        if entry["name"] == name:
            return entry
    return None


def list_tools_by_category(category: str) -> List[Dict[str, Any]]:
    return [t for t in TOOL_CATALOG if t["category"] == category]
